### PR TITLE
654 - adds helper text for geo, sra

### PR DESCRIPTION
**Pull request by davidsmejia**
## Issue Number

#654 

## Purpose/Implementation Notes

* makes the hints based on import source not import attribute
* Adds examples for geo and sra imports

## Types of changes

- New feature (non-breaking change which adds functionality)

## Functional tests

looked at them locally

## Checklist

- [X] Lint and unit tests pass locally with my changes

## Screenshots

Screen Shot 2021-01-14 at 11 38 33 AM
Screen Shot 2021-01-14 at 11 38 41 AM

### CODE REVIEW

**Comment by dvenprasad** [comment]
Can we
-  `ex` ----> `Examples` 
- add a GSM accession example to the helper text? 
Otherwise all good 👍

**Review by dvenprasad — APPROVED** [review]
Can we
ex ----> Examples
add a GSM accession example to the helper text?
Otherwise all good 👍

**Comment by davidsmejia** [comment]
Updated!

Screen Shot 2021-01-21 at 12 11 41 PM

**Comment by davidsmejia** [comment]
I did x or y or z because I didn't want someone to think that you could do coma separated codes

**Pull request merged**
