### PR TITLE
Try tweaking the way the README does directories

### PR DESCRIPTION
**Pull request by kurtwheeler**
I'm not sure I love this way either, but I was tired of having to remove `cd X &&` from every command I copied from the README.

I'd love to hear any ideas anyone has of better ways of specifying directories for commands in the README.

### CODE REVIEW

**Comment by arielsvn** [comment]
hmm our current `readme` is for the API project, would it be good to move it into that directory? And do the same in the `client/` folder? I imagine both projects will have different instructions to execute them.

**Comment by davidsmejia** [comment]
> hmm our current readme is for the API project, would it be good to move it into that directory? And do the same in the client/ folder? I imagine both projects will have different instructions to execute them.

I second this, I think we could have a general readme that links to the specific readmes in the various directories

**Comment by kurtwheeler** [comment]
That sounds good. I'm doing that in my materials PR because I wanted to add some additional API-specific documentation anyway.

**Comment by kurtwheeler** [comment]
I'm going to close this because #77 addresses this in a better way.

**Pull request closed without merging**
