### PR TITLE
resources related through organisation__id

### PR DESCRIPTION
**Pull request by davidsmejia**
## Issue Number

n/a @jashapiro was right

### CODE REVIEW

**Comment by jashapiro** [comment]
> ## Issue Number
> n/a @jashapiro was right

about what?

**Comment by davidsmejia** [comment]
related resources filtering by organization/team wasnt being applied because of a typo

**Review by kurtwheeler — APPROVED** [review]
LGTM!

**Comment by kurtwheeler** [comment]
Was there an issue reported for this?

**Pull request merged**
